# Generated by Django 4.2.7 on 2023-11-27 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('username', models.CharField(max_length=100)),
                ('contrasena', models.CharField(max_length=100)),
                ('tel', models.IntegerField()),
                ('fecha_nac', models.DateField()),
                ('tipo_doc', models.TextField()),
                ('num_doc', models.IntegerField()),
                ('correo', models.CharField(max_length=100)),
                ('casas_habitadas', models.IntegerField()),
            ],
        ),
    ]
