# Generated by Django 4.2.7 on 2023-12-02 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inmueble',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.TextField()),
                ('tamano', models.CharField(max_length=100)),
                ('direccion', models.CharField(max_length=100)),
                ('preciobase', models.IntegerField()),
                ('cupo', models.IntegerField()),
                ('servicios_base', models.TextField()),
                ('servicios_ad', models.TextField()),
                ('num_banos', models.IntegerField()),
                ('petfriendly', models.BooleanField()),
            ],
        ),
    ]
