# Generated by Django 4.2.7 on 2023-12-02 17:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_inmueble'),
    ]

    operations = [
        migrations.AddField(
            model_name='inmueble',
            name='arrendador',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='api.usuario'),
        ),
    ]
