# Generated by Django 4.2.7 on 2023-12-03 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_arriendo'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServicioAdicional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('precio', models.IntegerField()),
            ],
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='casas_habitadas',
        ),
        migrations.AddField(
            model_name='arriendo',
            name='total_a_pagar',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
