# Generated by Django 4.2.7 on 2023-12-03 05:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_servicioadicional_remove_usuario_casas_habitadas_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='servicioadicional',
            old_name='nombre',
            new_name='servicio',
        ),
        migrations.RemoveField(
            model_name='arriendo',
            name='total_a_pagar',
        ),
        migrations.AddField(
            model_name='servicioadicional',
            name='inmueble',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='api.inmueble'),
        ),
    ]
