# Generated by Django 4.2.7 on 2023-12-03 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_rename_nombre_servicioadicional_servicio_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Direccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direccion', models.CharField(max_length=100)),
                ('pais', models.CharField(default='Colombia', max_length=100)),
                ('ciudad', models.CharField(max_length=100)),
                ('departamento', models.CharField(max_length=100)),
                ('barrio', models.CharField(blank=True, max_length=100, null=True)),
                ('detalles_adicionales', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
